### ISSUE TITLE
Autoloader missing

### ISSUE THREAD

**Issue by tradesouthwest** [mbezuidenhout/woocommerce-bookings-extensions#1]
Can you tell us why the Autoloader is missing in /vendors/....? Plugin does not load any of the scripts without the autoloader file included. Thanks.

**Comment by mbezuidenhout** [comment]
Hi Larry,

The plug in wasn't designed to be installed with packagist. All the files for the package would normally sit in the wp-content/plugins/ directory. 

The extension has been uploaded to wordpress.org for you to install directory into wordpress. https://wordpress.org/plugins/woo-bookings-extensions/

If you give me some information on your set up I would be able to take a look into it.

**Comment by tradesouthwest** [comment]
Oh great, thanks for the update, Marius. Will look on w.org to check for next time I need this.

**Comment by tradesouthwest** [comment]
OOps left open. xI hard coded a solution but thanks for sharing your work on Github.
